#!/usr/bin/env python3
"""Generate src/sqc_element_data.f90 from the debyer element tables.

The tabulated numbers (masses, IT92 X-ray coefficients, NN92 bound coherent
neutron scattering lengths) are physical data compiled by the debyer project;
see the references below.  The C source itself is not redistributed here, only
the derived Fortran data table that this script rewrites mechanically.

Usage:
    tools/gen_element_data.py /path/to/debyer/debyer/atomtables.c src/sqc_element_data.f90

References
----------
* masses: CRC Handbook of Chemistry and Physics (63rd/70th ed.)
* X-ray:  International Tables for Crystallography, Vol. C (1992),
          Table 6.1.1.4 - analytical approximation to the scattering factors
          ("IT92" / Cromer-Mann a_i, b_i, c).
* neutron: Neutron News 3 (1992) 29-37, NIST table of bound coherent
          scattering lengths ("NN92").
"""

import re
import sys


def strip_comments(text):
    return re.sub(r"/\*.*?\*/", "", text, flags=re.S)


def grab_block(text, name):
    start = text.index(name)
    start = text.index("{", start)
    depth = 0
    for idx in range(start, len(text)):
        if text[idx] == "{":
            depth += 1
        elif text[idx] == "}":
            depth -= 1
            if depth == 0:
                return text[start : idx + 1]
    raise ValueError("unterminated block " + name)


def parse_pse(block):
    rows = {}
    for line in block.splitlines():
        m = re.match(r'\s*\{\s*(\d+)\s*,\s*"([^"]*)"\s*,\s*"([^"]*)"\s*,\s*([0-9.]+)\s*\}', line)
        if m:
            rows[m.group(2)] = (int(m.group(1)), m.group(3), float(m.group(4)))
    return rows


def parse_it92(block):
    rows = {}
    # rows look like: { "H", { a,a,a,a }, { b,b,b,b }, c },
    pattern = re.compile(
        r'\{\s*"([^"]*)"\s*,\s*\{([^}]*)\}\s*,\s*\{([^}]*)\}\s*,\s*([-0-9.eE+]+)\s*\}'
    )
    for m in pattern.finditer(block):
        a = [float(x) for x in m.group(2).split(",")]
        b = [float(x) for x in m.group(3).split(",")]
        rows[m.group(1)] = (a, b, float(m.group(4)))
    return rows


def parse_nn92(block):
    rows = {}
    pattern = re.compile(
        r'\{\s*"([^"]*)"\s*,\s*([-0-9.eE+]+)\s*,\s*([-0-9.eE+]+)\s*,\s*([-0-9.eE+]+)\s*\}'
    )
    for m in pattern.finditer(block):
        rows[m.group(1)] = float(m.group(2))
    return rows


def fortran_real(value):
    text = repr(float(value))
    if "e" in text or "E" in text:
        mantissa, exponent = re.split("[eE]", text)
        return "%sd%s" % (mantissa, int(exponent))
    return text + "d0"


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    source = strip_comments(open(sys.argv[1]).read())
    out_path = sys.argv[2]

    pse = parse_pse(grab_block(source, "pse_table[]"))
    it92 = parse_it92(grab_block(source, "it92_table[]"))
    nn92 = parse_nn92(grab_block(source, "nn92_table[]"))

    symbols = sorted(pse, key=lambda s: (pse[s][0], s))
    lines = []
    add = lines.append
    add("! Generated by tools/gen_element_data.py -- do not edit by hand.")
    add("!")
    add("! Sources of the tabulated data (via the debyer project):")
    add("!   masses  : CRC Handbook of Chemistry and Physics, 63rd/70th ed.")
    add("!   X-ray   : International Tables for Crystallography C (1992), 6.1.1.4")
    add("!   neutron : Neutron News 3 (1992) 29-37 (NIST bound coherent lengths)")
    add("module sqc_element_data")
    add("   use sqc_kinds, only: rk")
    add("   implicit none")
    add("   private")
    add("")
    add("   integer, parameter, public :: n_elements = %d" % len(symbols))
    add("")
    add("   ! Atomic number, symbol, name and atomic mass of each entry.")
    add("   integer, parameter, public :: element_z(n_elements) = [ &")
    add(_wrapped(["%d" % pse[s][0] for s in symbols], "      "))
    add("   character(len=2), parameter, public :: element_symbol(n_elements) = [ &")
    add(_wrapped(['"%-2s"' % s for s in symbols], "      "))
    add("   character(len=16), parameter, public :: element_name(n_elements) = [ &")
    add(_wrapped(['"%-16s"' % pse[s][1] for s in symbols], "      "))
    add("   real(rk), parameter, public :: element_mass(n_elements) = [ &")
    add(_wrapped([fortran_real(pse[s][2]) for s in symbols], "      "))
    add("")
    add("   ! Bound coherent neutron scattering length [fm]; 0 if not tabulated.")
    add("   real(rk), parameter, public :: element_neutron_b(n_elements) = [ &")
    add(_wrapped([fortran_real(nn92.get(s, 0.0)) for s in symbols], "      "))
    add("   logical, parameter, public :: element_has_neutron(n_elements) = [ &")
    add(_wrapped(["%s" % (".true." if s in nn92 else ".false.") for s in symbols], "      "))
    add("")
    add("   ! X-ray IT92 (Cromer-Mann) coefficients: f(q) = sum_i a_i exp(-b_i (q/4pi)^2) + c")
    add("   real(rk), parameter, public :: element_xray_a(4, n_elements) = reshape([ &")
    add(_wrapped([fortran_real(x) for s in symbols for x in it92.get(s, ([0.0] * 4, [0.0] * 4, 0.0))[0]], "      ", closer=" &"))
    add("     ], [4, n_elements])")
    add("   real(rk), parameter, public :: element_xray_b(4, n_elements) = reshape([ &")
    add(_wrapped([fortran_real(x) for s in symbols for x in it92.get(s, ([0.0] * 4, [0.0] * 4, 0.0))[1]], "      ", closer=" &"))
    add("     ], [4, n_elements])")
    add("   real(rk), parameter, public :: element_xray_c(n_elements) = [ &")
    add(_wrapped([fortran_real(it92.get(s, ([0.0] * 4, [0.0] * 4, 0.0))[2]) for s in symbols], "      "))
    add("   logical, parameter, public :: element_has_xray(n_elements) = [ &")
    add(_wrapped(["%s" % (".true." if s in it92 else ".false.") for s in symbols], "      "))
    add("")
    add("end module sqc_element_data")
    add("")

    with open(out_path, "w") as handle:
        handle.write("\n".join(lines))

    missing_xray = [s for s in symbols if s not in it92]
    missing_neutron = [s for s in symbols if s not in nn92]
    sys.stderr.write(
        "%s: %d elements, %d without X-ray data, %d without neutron data\n"
        % (out_path, len(symbols), len(missing_xray), len(missing_neutron))
    )


def _wrapped(items, indent, per_line=4, closer=" ]"):
    """Format a Fortran array constructor body, a few items per line.

    The last line is terminated with `closer`: either the closing bracket, or a
    continuation marker when the caller writes the bracket on the next line.
    """
    out = []
    for start in range(0, len(items), per_line):
        chunk = items[start : start + per_line]
        last = start + per_line >= len(items)
        sep = "" if last else ","
        out.append(indent + ", ".join(chunk) + sep + (closer if last else " &"))
    return "\n".join(out)


if __name__ == "__main__":
    main()
